name = "vds2"
main = "src/worker/index.js"
compatibility_date = "2024-12-01"

[vars]
ENVIRONMENT = "development"
REDDIT_CLIENT_ID_DEV = "E8uoappKT2d220SGMGGCrQ"
REDDIT_CLIENT_ID_STAGING = "4RAO1QXtJma39GdP-dyQwg"
REDDIT_CLIENT_ID_PROD = "LSKIVaIEdblNdyOVY10n4Q"

# Static assets from Gatsby build
[assets]
directory = "public/"
not_found_handling = "single-page-application"
binding = "ASSETS"

# Database binding for D1 (production)
[[d1_databases]]
binding = "DB"
database_name = "vds-db"
database_id = "2c5b844c-7332-4634-b53c-7fc236528778"

# For local development, use --local flag with wrangler dev
# This will use the local database files instead

[observability.logs]
enabled = true
